-- Initial schema for the MOTION backend.
-- Keep quoted table names where the Node.js code uses mixed-case identifiers.

create table if not exists public.motion24_kementerian (
	id_kementerian integer generated by default as identity primary key,
	kementerian text not null,
	singkatan text not null unique,
	created_at timestamptz not null default now()
);

create table if not exists public.motion24_jabatan (
	id_jabatan integer generated by default as identity primary key,
	jabatan text not null unique,
	created_at timestamptz not null default now()
);

create table if not exists public.motion24_proker (
	id_proker integer generated by default as identity primary key,
	proker text not null,
	id_kementerian integer not null references public.motion24_kementerian(id_kementerian) on update cascade on delete restrict,
	created_at timestamptz not null default now()
);

create table if not exists public."motion24_anggotaBEM" (
	nim text primary key,
	nama text not null,
	foto text not null default '',
	id_jabatan integer references public.motion24_jabatan(id_jabatan) on update cascade on delete set null,
	id_kementerian integer references public.motion24_kementerian(id_kementerian) on update cascade on delete set null,
	created_at timestamptz not null default now()
);

create table if not exists public."motion24_pjProker" (
	nim text not null references public."motion24_anggotaBEM"(nim) on update cascade on delete cascade,
	id_proker integer not null references public.motion24_proker(id_proker) on update cascade on delete cascade,
	created_at timestamptz not null default now(),
	primary key (nim, id_proker)
);

create table if not exists public.motion24_kegiatan (
	id_kegiatan integer generated by default as identity primary key,
	kegiatan text not null,
	id_kementerian integer not null references public.motion24_kementerian(id_kementerian) on update cascade on delete restrict,
	tanggal date,
	created_at timestamptz not null default now()
);

create table if not exists public.motion24_aspek (
	id_aspek integer generated by default as identity primary key,
	aspek text not null,
	indikator text,
	id_jabatan integer references public.motion24_jabatan(id_jabatan) on update cascade on delete set null,
	created_at timestamptz not null default now()
);

create table if not exists public."motion24_detailAspek" (
	id_subaspek integer generated by default as identity primary key,
	id_aspek integer not null references public.motion24_aspek(id_aspek) on update cascade on delete cascade,
	sub_aspek text not null,
	deskripsi text,
	created_at timestamptz not null default now()
);

create table if not exists public.motion24_rapor (
	id_rapor integer generated by default as identity primary key,
	rapor_ke integer not null,
	hobi text,
	kesimpulan_diri text,
	keterangan_absen text,
	motivasi text,
	nim text not null references public."motion24_anggotaBEM"(nim) on update cascade on delete cascade,
	created_at timestamptz not null default now(),
	unique (nim, rapor_ke)
);

create table if not exists public.motion24_absensi (
	id_absensi integer generated by default as identity primary key,
	id_kegiatan integer not null references public.motion24_kegiatan(id_kegiatan) on update cascade on delete cascade,
	nim text not null references public."motion24_anggotaBEM"(nim) on update cascade on delete cascade,
	status text not null default 'alpha' check (status in ('hadir', 'surat_sakit', 'sakit', 'izin', 'alpha')),
	created_at timestamptz not null default now(),
	unique (id_kegiatan, nim)
);

create table if not exists public.motion24_transparansi (
	id_transparansi integer generated by default as identity primary key,
	id_rapor integer not null references public.motion24_rapor(id_rapor) on update cascade on delete cascade,
	id_aspek integer not null references public.motion24_aspek(id_aspek) on update cascade on delete cascade,
	catatan_transparansi text,
	created_at timestamptz not null default now(),
	unique (id_rapor, id_aspek)
);

create table if not exists public.motion24_nilai (
	id_nilai integer generated by default as identity primary key,
	id_rapor integer not null references public.motion24_rapor(id_rapor) on update cascade on delete cascade,
	id_subaspek integer not null references public."motion24_detailAspek"(id_subaspek) on update cascade on delete cascade,
	nilai numeric(5, 2) not null,
	created_at timestamptz not null default now(),
	unique (id_rapor, id_subaspek)
);

create table if not exists public."motion24_bestStaff" (
	id integer generated by default as identity primary key,
	phase integer not null check (phase between 1 and 3),
	nim text not null references public."motion24_anggotaBEM"(nim) on update cascade on delete cascade,
	id_kementerian integer not null references public.motion24_kementerian(id_kementerian) on update cascade on delete cascade,
	created_at timestamptz not null default now(),
	unique (phase, id_kementerian)
);

create table if not exists public.motion24_admin (
	nim text primary key references public."motion24_anggotaBEM"(nim) on update cascade on delete cascade,
	created_at timestamptz not null default now()
);

create index if not exists idx_motion24_anggota_bem_jabatan on public."motion24_anggotaBEM"(id_jabatan);
create index if not exists idx_motion24_anggota_bem_kementerian on public."motion24_anggotaBEM"(id_kementerian);
create index if not exists idx_motion24_proker_kementerian on public.motion24_proker(id_kementerian);
create index if not exists idx_motion24_kegiatan_kementerian_tanggal on public.motion24_kegiatan(id_kementerian, tanggal);
create index if not exists idx_motion24_rapor_nim on public.motion24_rapor(nim);
create index if not exists idx_motion24_absensi_nim on public.motion24_absensi(nim);
create index if not exists idx_motion24_transparansi_rapor on public.motion24_transparansi(id_rapor);
create index if not exists idx_motion24_nilai_rapor on public.motion24_nilai(id_rapor);
create index if not exists idx_motion24_detail_aspek_aspek on public."motion24_detailAspek"(id_aspek);

alter table public.motion24_kementerian enable row level security;
alter table public.motion24_jabatan enable row level security;
alter table public.motion24_proker enable row level security;
alter table public."motion24_anggotaBEM" enable row level security;
alter table public."motion24_pjProker" enable row level security;
alter table public.motion24_kegiatan enable row level security;
alter table public.motion24_aspek enable row level security;
alter table public."motion24_detailAspek" enable row level security;
alter table public.motion24_rapor enable row level security;
alter table public.motion24_absensi enable row level security;
alter table public.motion24_transparansi enable row level security;
alter table public.motion24_nilai enable row level security;
alter table public."motion24_bestStaff" enable row level security;
alter table public.motion24_admin enable row level security;

grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
	'motion24_bucket',
	'motion24_bucket',
	true,
	5242880,
	array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
	public = excluded.public,
	file_size_limit = excluded.file_size_limit,
	allowed_mime_types = excluded.allowed_mime_types;
